name: Release

on:
  push:
    tags: [ 'v*' ]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Config
        id: config
        run: |
          echo explorer.alerta.io >./app/CNAME
          cat >./app/config.js << EOF
          'use strict';
          angular.module('config', [])
            .constant('config', {
              'endpoint': "https://alerta-api.fly.dev",
              'key': 'tQw6PGFKirWz5WtCZvI-CiHdVBLstnwPVLasFjMH',
            });
          EOF
          sed -i 's/@@TRACKING_ID/UA-44644195-4/' ./app/index.html
      - name: Deploy
        id: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app
      - uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
